import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  backendSidebar: [
    {
      type: "category",
      label: "Backend",
      collapsed: false,
      items: [
        { type: "autogenerated", dirName: "backend" },
      ],
    },
  ],
  frontendSidebar: [
    {
      type: "category",
      label: "Frontend",
      collapsed: false,
      items: [
        { type: "autogenerated", dirName: "frontend" },
      ],
    },
  ],
  backofficeAndCoreSidebar: [
    {
      type: "category",
      label: "Backoffice",
      collapsed: false,
      items: [
        { type: "autogenerated", dirName: "backoffice" },
      ],
    },
    {
      type: "category",
      label: "Core",
      collapsed: true,
      items: [
        { type: "autogenerated", dirName: "core" },
      ],
    },
    {
      type: "category",
      label: "Finance",
      collapsed: true,
      items: [
        { type: "autogenerated", dirName: "finance" },
      ],
    },
  ],
}

export default sidebars
