/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "WorkmateOS Docs",
  "tagline": "Interne Entwicklerdokumentation — K.I.T. Solutions",
  "favicon": "img/favicon.ico",
  "url": "https://K-I-T-Solutions.github.io",
  "baseUrl": "/workmate_os/",
  "organizationName": "K-I-T-Solutions",
  "projectName": "workmate_os",
  "trailingSlash": false,
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "markdown": {
    "format": "md",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "../docs/wiki",
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/K-I-T-Solutions/workmate_os/edit/main/docs/wiki/",
          "exclude": [
            "**/ui/**",
            "**/design/**"
          ]
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/workmate-social.png",
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "WorkmateOS",
      "logo": {
        "alt": "K.I.T. Solutions Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "backendSidebar",
          "position": "left",
          "label": "Backend"
        },
        {
          "type": "docSidebar",
          "sidebarId": "frontendSidebar",
          "position": "left",
          "label": "Frontend"
        },
        {
          "type": "docSidebar",
          "sidebarId": "backofficeAndCoreSidebar",
          "position": "left",
          "label": "Backoffice & Core"
        },
        {
          "href": "https://api.workmate.kit-it-koblenz.de/docs",
          "label": "API (Swagger)",
          "position": "right"
        },
        {
          "href": "https://github.com/K-I-T-Solutions/workmate_os",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Dokumentation",
          "items": [
            {
              "label": "Backend",
              "to": "/backend/AUTHENTICATION"
            },
            {
              "label": "Frontend",
              "to": "/frontend/README"
            },
            {
              "label": "Module",
              "to": "/backend/MODULE_UEBERSICHT"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "WorkmateOS",
              "href": "https://workmate.kit-it-koblenz.de"
            },
            {
              "label": "API Docs",
              "href": "https://api.workmate.kit-it-koblenz.de/docs"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/K-I-T-Solutions/workmate_os"
            }
          ]
        }
      ],
      "copyright": "© 2026 K.I.T. Solutions · Built with Docusaurus"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "sql",
        "typescript",
        "yaml",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
