"""add dashboard related models

Revision ID: 704920992d2c
Revises: e2e241902178
Create Date: 2025-12-02 20:52:24.505652+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '704920992d2c'
down_revision: Union[str, None] = 'e2e241902178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_entries_owner_id'), 'activity_entries', ['owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_owner_id'), 'notifications', ['owner_id'], unique=False)
    op.create_table('os_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('sidebar_collapsed', sa.Boolean(), nullable=False),
    sa.Column('theme_mode', sa.String(), nullable=False),
    sa.Column('favorite_apps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dock_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wallpaper', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.alter_column('chat_messages', 'is_system_message',
               existing_type=sa.BOOLEAN(),
               comment="System-Nachricht (z.B. 'Status geändert zu Active')",
               existing_comment='System-Nachricht',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Nachrichtentyp (text, file, system)',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('chat_messages', 'attachment_path',
               existing_type=sa.TEXT(),
               comment='Pfad zu angehängter Datei',
               existing_comment='Pfad zu Datei-Anhang',
               existing_nullable=True)
    op.alter_column('chat_messages', 'project_id',
               existing_type=sa.UUID(),
               comment='Zugehöriges Projekt',
               existing_nullable=False)
    op.alter_column('chat_messages', 'author_id',
               existing_type=sa.UUID(),
               comment='Verfasser der Nachricht',
               existing_nullable=False)
    op.alter_column('chat_messages', 'reply_to_id',
               existing_type=sa.UUID(),
               comment='Referenz zu einer anderen Nachricht (für Threads)',
               existing_nullable=True)
    op.alter_column('dashboards', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('dashboards', 'widgets_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('dashboards', 'layout_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('dashboards', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.alter_column('number_sequences', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Dokumenttyp: invoice, quote, credit_note, cancellation, etc.',
               existing_nullable=False)
    op.alter_column('number_sequences', 'year',
               existing_type=sa.INTEGER(),
               comment='Jahreszahl für den Nummernkreis',
               existing_nullable=False)
    op.alter_column('number_sequences', 'current_number',
               existing_type=sa.INTEGER(),
               comment='Letzte vergebene laufende Nummer',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('number_sequences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('number_sequences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_number_sequences_doc_type_year', table_name='number_sequences')
    op.create_index(op.f('ix_number_sequences_doc_type'), 'number_sequences', ['doc_type'], unique=False)
    op.create_index(op.f('ix_number_sequences_year'), 'number_sequences', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_number_sequences_year'), table_name='number_sequences')
    op.drop_index(op.f('ix_number_sequences_doc_type'), table_name='number_sequences')
    op.create_index('ix_number_sequences_doc_type_year', 'number_sequences', ['doc_type', 'year'], unique=False)
    op.alter_column('number_sequences', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('number_sequences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('number_sequences', 'current_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Letzte vergebene laufende Nummer',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('number_sequences', 'year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Jahreszahl für den Nummernkreis',
               existing_nullable=False)
    op.alter_column('number_sequences', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Dokumenttyp: invoice, quote, credit_note, cancellation, etc.',
               existing_nullable=False)
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.alter_column('dashboards', 'theme',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dashboards', 'layout_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('dashboards', 'widgets_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('dashboards', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_messages', 'reply_to_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Referenz zu einer anderen Nachricht (für Threads)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'author_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Verfasser der Nachricht',
               existing_nullable=False)
    op.alter_column('chat_messages', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Zugehöriges Projekt',
               existing_nullable=False)
    op.alter_column('chat_messages', 'attachment_path',
               existing_type=sa.TEXT(),
               comment='Pfad zu Datei-Anhang',
               existing_comment='Pfad zu angehängter Datei',
               existing_nullable=True)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nachrichtentyp (text, file, system)',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('chat_messages', 'is_system_message',
               existing_type=sa.BOOLEAN(),
               comment='System-Nachricht',
               existing_comment="System-Nachricht (z.B. 'Status geändert zu Active')",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('user_settings')
    op.drop_table('os_preferences')
    op.drop_index(op.f('ix_notifications_owner_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_activity_entries_owner_id'), table_name='activity_entries')
    op.drop_table('activity_entries')
    # ### end Alembic commands ###