"""Fix Invoice-Expense relationship

Revision ID: 0c0b8f566bc5
Revises: 125fa6792712
Create Date: 2025-10-24 12:24:40.157461+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0b8f566bc5'
down_revision: Union[str, None] = '125fa6792712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###