"""Add invoices and payments tables

Revision ID: 452a56fe4f4d
Revises: 0c0b8f566bc5
Create Date: 2025-10-24 13:31:12.648259+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452a56fe4f4d'
down_revision: Union[str, None] = '0c0b8f566bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###