"""phase2_improved_models

Revision ID: d188e9469e64
Revises: 452a56fe4f4d
Create Date: 2025-10-30 21:06:44.323581+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd188e9469e64'
down_revision: Union[str, None] = '452a56fe4f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_is_primary', table_name='contacts')
    op.create_index('ix_contacts_lastname', 'contacts', ['lastname'], unique=False)
    op.create_index('ix_one_primary_contact_per_customer', 'contacts', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index('ix_customers_type', 'customers', ['type'], unique=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default='0.00',
               existing_comment='Gesamtbetrag inkl. MwSt',
               existing_nullable=False)
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.add_column('projects', sa.Column('priority', sa.String(length=50), server_default='medium', nullable=False, comment='Priorität: low, medium, high, urgent'))
    op.alter_column('projects', 'customer_id',
               existing_type=sa.UUID(),
               comment='Zugehöriger Kunde',
               existing_nullable=False)
    op.alter_column('projects', 'department_id',
               existing_type=sa.UUID(),
               comment='Zugehörige Abteilung',
               existing_nullable=True)
    op.alter_column('projects', 'project_manager_id',
               existing_type=sa.UUID(),
               comment='Verantwortlicher Projektmanager',
               existing_comment='Responsible project manager',
               existing_nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Projekttitel',
               existing_nullable=False)
    op.alter_column('projects', 'project_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Eindeutige Projektnummer (z.B. PRJ-2025-001)',
               existing_comment='Unique project identifier like PRJ-2025-001',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default='planning',
               comment='Status: planning, active, on_hold, completed, cancelled',
               existing_comment='planning, active, on_hold, completed, cancelled',
               existing_nullable=False)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               comment='Projektstartdatum',
               existing_nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=sa.DATE(),
               comment='Geplantes Projektende',
               existing_nullable=True)
    op.alter_column('projects', 'deadline',
               existing_type=sa.DATE(),
               comment='Finale Deadline',
               existing_comment='Final deadline',
               existing_nullable=True)
    op.alter_column('projects', 'budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Gesamtbudget in EUR',
               existing_comment='Total project budget in EUR',
               existing_nullable=True)
    op.alter_column('projects', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Standard-Stundensatz für Abrechnung',
               existing_comment='Default hourly rate for billing',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment='Projektbeschreibung',
               existing_nullable=True)
    op.alter_column('projects', 'notes',
               existing_type=sa.TEXT(),
               comment='Interne Notizen',
               existing_comment='Internal notes',
               existing_nullable=True)
    op.create_index('ix_projects_deadline', 'projects', ['deadline'], unique=False)
    op.create_index('ix_projects_priority', 'projects', ['priority'], unique=False)
    op.create_index('ix_projects_project_manager_id', 'projects', ['project_manager_id'], unique=False)
    op.create_index('ix_projects_project_number', 'projects', ['project_number'], unique=False)
    op.create_index('ix_projects_start_date', 'projects', ['start_date'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_start_date', table_name='projects')
    op.drop_index('ix_projects_project_number', table_name='projects')
    op.drop_index('ix_projects_project_manager_id', table_name='projects')
    op.drop_index('ix_projects_priority', table_name='projects')
    op.drop_index('ix_projects_deadline', table_name='projects')
    op.alter_column('projects', 'notes',
               existing_type=sa.TEXT(),
               comment='Internal notes',
               existing_comment='Interne Notizen',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Projektbeschreibung',
               existing_nullable=True)
    op.alter_column('projects', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Default hourly rate for billing',
               existing_comment='Standard-Stundensatz für Abrechnung',
               existing_nullable=True)
    op.alter_column('projects', 'budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Total project budget in EUR',
               existing_comment='Gesamtbudget in EUR',
               existing_nullable=True)
    op.alter_column('projects', 'deadline',
               existing_type=sa.DATE(),
               comment='Final deadline',
               existing_comment='Finale Deadline',
               existing_nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Geplantes Projektende',
               existing_nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Projektstartdatum',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='planning, active, on_hold, completed, cancelled',
               existing_comment='Status: planning, active, on_hold, completed, cancelled',
               existing_nullable=False)
    op.alter_column('projects', 'project_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique project identifier like PRJ-2025-001',
               existing_comment='Eindeutige Projektnummer (z.B. PRJ-2025-001)',
               existing_nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Projekttitel',
               existing_nullable=False)
    op.alter_column('projects', 'project_manager_id',
               existing_type=sa.UUID(),
               comment='Responsible project manager',
               existing_comment='Verantwortlicher Projektmanager',
               existing_nullable=True)
    op.alter_column('projects', 'department_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Zugehörige Abteilung',
               existing_nullable=True)
    op.alter_column('projects', 'customer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Zugehöriger Kunde',
               existing_nullable=False)
    op.drop_column('projects', 'priority')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_comment='Gesamtbetrag inkl. MwSt',
               existing_nullable=False)
    op.drop_index('ix_customers_type', table_name='customers')
    op.drop_index('ix_one_primary_contact_per_customer', table_name='contacts', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('ix_contacts_lastname', table_name='contacts')
    op.create_index('ix_contacts_is_primary', 'contacts', ['customer_id', 'is_primary'], unique=False)
    # ### end Alembic commands ###