"""add title field into expenses

Revision ID: dfa1af733b20
Revises: 704920992d2c
Create Date: 2025-12-17 16:00:56.661744+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa1af733b20'
down_revision: Union[str, None] = '704920992d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               comment='Bezeichnung der kosten',
               existing_comment='Kurztitel der Ausgabe',
               existing_nullable=False)
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.alter_column('expenses', 'title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               comment='Kurztitel der Ausgabe',
               existing_comment='Bezeichnung der kosten',
               existing_nullable=False)
    # ### end Alembic commands ###