"""Smoke test – full auto discovery

Revision ID: 125fa6792712
Revises: fe86e095330a
Create Date: 2025-10-24 12:12:07.366335+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125fa6792712'
down_revision: Union[str, None] = 'fe86e095330a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_hours_templates',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('monday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('tuesday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('wednesday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('thursday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('friday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('saturday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('sunday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total hours per week'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_hours_templates_employee_id'), 'working_hours_templates', ['employee_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True, comment='Optional - for internal time without project'),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duration in minutes'),
    sa.Column('billable', sa.Boolean(), nullable=False, comment='Can this time be billed to customer?'),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Rate for this entry'),
    sa.Column('note', sa.Text(), nullable=True, comment='What was worked on'),
    sa.Column('task_type', sa.String(length=100), nullable=True, comment='development, meeting, support, documentation, etc.'),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_invoiced', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_project_id'), 'time_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_start_time'), 'time_entries', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_start_time'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_project_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_employee_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_working_hours_templates_employee_id'), table_name='working_hours_templates')
    op.drop_table('working_hours_templates')
    # ### end Alembic commands ###