"""Add Backoffice modules (CRM, Projects, Finance, Chat)

Revision ID: fe86e095330a
Revises: d760b7894323
Create Date: 2025-10-24 12:02:42.711520+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe86e095330a'
down_revision: Union[str, None] = 'd760b7894323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Kundenname / Firmenname'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='Kundentyp: business, individual, government'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Haupt-E-Mail Adresse'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Telefonnummer'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Webseite'),
    sa.Column('tax_id', sa.String(length=100), nullable=True, comment='Steuernummer / USt-IdNr'),
    sa.Column('street', sa.String(length=255), nullable=True, comment='Straße und Hausnummer'),
    sa.Column('zip_code', sa.String(length=20), nullable=True, comment='Postleitzahl'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='Stadt'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Land'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Interne Notizen'),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False, comment='Status: active, inactive, lead, blocked'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_index('ix_customers_status', 'customers', ['status'], unique=False)
    op.create_index('ix_customers_tax_id', 'customers', ['tax_id'], unique=False)
    op.create_table('contacts',
    sa.Column('customer_id', sa.Uuid(), nullable=False, comment='Zugehöriger Kunde'),
    sa.Column('firstname', sa.String(length=100), nullable=False, comment='Vorname'),
    sa.Column('lastname', sa.String(length=100), nullable=False, comment='Nachname'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='E-Mail Adresse'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Telefonnummer'),
    sa.Column('mobile', sa.String(length=50), nullable=True, comment='Mobilnummer'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Position im Unternehmen'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Abteilung'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notizen zum Kontakt'),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False, comment='Hauptansprechpartner für diesen Kunden'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_customer_id', 'contacts', ['customer_id'], unique=False)
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_is_primary', 'contacts', ['customer_id', 'is_primary'], unique=False)
    op.create_table('projects',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('project_manager_id', sa.UUID(), nullable=True, comment='Responsible project manager'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_number', sa.String(length=50), nullable=True, comment='Unique project identifier like PRJ-2025-001'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='planning, active, on_hold, completed, cancelled'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True, comment='Final deadline'),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total project budget in EUR'),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Default hourly rate for billing'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_number')
    )
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_projects_department_id'), 'projects', ['department_id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message', sa.Text(), nullable=False, comment='Nachrichteninhalt'),
    sa.Column('is_system_message', sa.Boolean(), server_default='false', nullable=False, comment="System-Nachricht (z.B. 'Status geändert zu Active')"),
    sa.Column('message_type', sa.String(length=50), server_default='text', nullable=False, comment='Nachrichtentyp (text, file, system)'),
    sa.Column('attachment_path', sa.Text(), nullable=True, comment='Pfad zu angehängter Datei'),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Zugehöriges Projekt'),
    sa.Column('author_id', sa.UUID(), nullable=False, comment='Verfasser der Nachricht'),
    sa.Column('reply_to_id', sa.Uuid(), nullable=True, comment='Referenz zu einer anderen Nachricht (für Threads)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_author_id', 'chat_messages', ['author_id'], unique=False)
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_project_id', 'chat_messages', ['project_id'], unique=False)
    op.create_index('ix_chat_messages_reply_to_id', 'chat_messages', ['reply_to_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Eindeutige Rechnungsnummer (z.B. RE-2025-001)'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Gesamtbetrag inkl. MwSt'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False, comment='Zwischensumme ohne MwSt'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False, comment='MwSt-Betrag'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='Status: draft, sent, paid, partial, overdue, cancelled'),
    sa.Column('issued_date', sa.Date(), nullable=True, comment='Rechnungsdatum'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Fälligkeitsdatum'),
    sa.Column('pdf_path', sa.Text(), nullable=True, comment='Pfad zur generierten PDF-Rechnung'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Interne Notizen'),
    sa.Column('terms', sa.Text(), nullable=True, comment='Zahlungsbedingungen und AGB'),
    sa.Column('customer_id', sa.Uuid(), nullable=False, comment='Zugehöriger Kunde'),
    sa.Column('project_id', sa.Uuid(), nullable=True, comment='Optional zugehöriges Projekt'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total >= 0', name='check_invoice_total_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_issued_date', 'invoices', ['issued_date'], unique=False)
    op.create_index('ix_invoices_project_id', 'invoices', ['project_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('expenses',
    sa.Column('category', sa.String(length=50), nullable=False, comment='Ausgabenkategorie (travel, material, software, etc.)'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Ausgabenbetrag'),
    sa.Column('description', sa.Text(), nullable=False, comment='Beschreibung der Ausgabe'),
    sa.Column('receipt_path', sa.Text(), nullable=True, comment='Pfad zum Beleg/Quittung (PDF, Bild)'),
    sa.Column('note', sa.Text(), nullable=True, comment='Zusätzliche Notizen'),
    sa.Column('is_billable', sa.Boolean(), server_default='true', nullable=False, comment='Kann an Kunden weiterberechnet werden'),
    sa.Column('project_id', sa.Uuid(), nullable=True, comment='Optional zugehöriges Projekt'),
    sa.Column('invoice_id', sa.Uuid(), nullable=True, comment='Optional zugehörige Rechnung (wenn bereits abgerechnet)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_expense_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_created_at', 'expenses', ['created_at'], unique=False)
    op.create_index('ix_expenses_invoice_id', 'expenses', ['invoice_id'], unique=False)
    op.create_index('ix_expenses_project_id', 'expenses', ['project_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('position', sa.Integer(), nullable=False, comment='Sortierungsreihenfolge'),
    sa.Column('description', sa.Text(), nullable=False, comment='Leistungsbeschreibung'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Menge/Anzahl'),
    sa.Column('unit', sa.String(length=50), server_default='Stück', nullable=False, comment='Einheit (z.B. Stunden, Stück, m²)'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Einzelpreis netto'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='19.00', nullable=False, comment='MwSt-Satz in Prozent'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False, comment='Rabatt in Prozent'),
    sa.Column('invoice_id', sa.Uuid(), nullable=False, comment='Zugehörige Rechnung'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='check_discount_valid'),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.CheckConstraint('tax_rate >= 0', name='check_tax_rate_positive'),
    sa.CheckConstraint('unit_price >= 0', name='check_unit_price_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_line_items_invoice_id', 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_line_items_position', 'invoice_line_items', ['invoice_id', 'position'], unique=False)
    op.create_table('payments',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Zahlungsbetrag'),
    sa.Column('payment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='Datum des Zahlungseingangs'),
    sa.Column('method', sa.String(length=50), nullable=True, comment='Zahlungsmethode (cash, bank_transfer, etc.)'),
    sa.Column('reference', sa.String(length=100), nullable=True, comment='Buchungsreferenz (z.B. Transaktions-ID, Verwendungszweck)'),
    sa.Column('note', sa.Text(), nullable=True, comment='Interne Notiz zum Zahlungseingang'),
    sa.Column('invoice_id', sa.Uuid(), nullable=False, comment='Zugehörige Rechnung'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_payment_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_method', 'payments', ['method'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_method', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoice_line_items_position', table_name='invoice_line_items')
    op.drop_index('ix_invoice_line_items_invoice_id', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_expenses_project_id', table_name='expenses')
    op.drop_index('ix_expenses_invoice_id', table_name='expenses')
    op.drop_index('ix_expenses_created_at', table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_project_id', table_name='invoices')
    op.drop_index('ix_invoices_issued_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_chat_messages_reply_to_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_project_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_index('ix_chat_messages_author_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_department_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_contacts_is_primary', table_name='contacts')
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_index('ix_contacts_customer_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_customers_tax_id', table_name='customers')
    op.drop_index('ix_customers_status', table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###