"""add_email_settings_to_system_settings

Revision ID: 1c40c9b9cff5
Revises: 578d03552aae
Create Date: 2026-01-14 22:28:23.826757+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c40c9b9cff5'
down_revision: Union[str, None] = '578d03552aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable first
    op.add_column('system_settings', sa.Column('email_enabled', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_host', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_username', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_password', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_from_email', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_from_name', sa.String(length=200), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_use_tls', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True))

    # Step 2: Set default values for existing rows
    op.execute("UPDATE system_settings SET email_enabled = false WHERE email_enabled IS NULL")
    op.execute("UPDATE system_settings SET smtp_port = 587 WHERE smtp_port IS NULL")
    op.execute("UPDATE system_settings SET smtp_from_name = 'WorkmateOS' WHERE smtp_from_name IS NULL")
    op.execute("UPDATE system_settings SET smtp_use_tls = true WHERE smtp_use_tls IS NULL")
    op.execute("UPDATE system_settings SET smtp_use_ssl = false WHERE smtp_use_ssl IS NULL")
    op.execute("UPDATE system_settings SET smtp_host = '' WHERE smtp_host IS NULL")
    op.execute("UPDATE system_settings SET smtp_username = '' WHERE smtp_username IS NULL")
    op.execute("UPDATE system_settings SET smtp_password = '' WHERE smtp_password IS NULL")
    op.execute("UPDATE system_settings SET smtp_from_email = '' WHERE smtp_from_email IS NULL")

    # Step 3: Alter columns to NOT NULL
    op.alter_column('system_settings', 'email_enabled', nullable=False)
    op.alter_column('system_settings', 'smtp_use_tls', nullable=False)
    op.alter_column('system_settings', 'smtp_use_ssl', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'smtp_use_ssl')
    op.drop_column('system_settings', 'smtp_use_tls')
    op.drop_column('system_settings', 'smtp_from_name')
    op.drop_column('system_settings', 'smtp_from_email')
    op.drop_column('system_settings', 'smtp_password')
    op.drop_column('system_settings', 'smtp_username')
    op.drop_column('system_settings', 'smtp_port')
    op.drop_column('system_settings', 'smtp_host')
    op.drop_column('system_settings', 'email_enabled')
    # ### end Alembic commands ###