"""Add HR leave management module

Revision ID: a8904a298e14
Revises: 809c073889c6
Create Date: 2026-01-08 15:56:14.986236+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8904a298e14'
down_revision: Union[str, None] = '809c073889c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_table('products')
    op.alter_column('stripe_config', 'test_mode',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Test Mode (true) or Live Mode (false)',
               existing_nullable=False)
    op.alter_column('stripe_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Config aktiv/inaktiv',
               existing_nullable=False)
    op.drop_index('ix_stripe_config_is_active', table_name='stripe_config')
    op.alter_column('system_settings', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'company_legal',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'tax_number',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'address_street',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'address_zip',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'address_city',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'address_country',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'company_email',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'company_phone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'company_website',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_settings', 'default_timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'default_currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'date_format',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'working_hours_per_day',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'working_days_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'vacation_days_per_year',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'weekend_saturday',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'weekend_sunday',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'maintenance_mode',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'allow_registration',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_settings', 'require_email_verification',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('time_entries', 'billable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Can this time be billed to customer?',
               existing_nullable=False)
    op.alter_column('time_entries', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('time_entries', 'is_invoiced',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'monday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'tuesday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'wednesday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'thursday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'friday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'saturday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'sunday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'weekly_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_comment='Total hours per week',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('working_hours_templates', 'weekly_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('40.0'),
               existing_comment='Total hours per week',
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'sunday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'saturday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'friday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('8.0'),
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'thursday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('8.0'),
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'wednesday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('8.0'),
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'tuesday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('8.0'),
               existing_nullable=False)
    op.alter_column('working_hours_templates', 'monday_hours',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('8.0'),
               existing_nullable=False)
    op.alter_column('time_entries', 'is_invoiced',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('time_entries', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('time_entries', 'billable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Can this time be billed to customer?',
               existing_nullable=False)
    op.alter_column('system_settings', 'require_email_verification',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('system_settings', 'allow_registration',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('system_settings', 'maintenance_mode',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('system_settings', 'weekend_sunday',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('system_settings', 'weekend_saturday',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('system_settings', 'vacation_days_per_year',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('system_settings', 'working_days_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('system_settings', 'working_hours_per_day',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8'),
               existing_nullable=False)
    op.alter_column('system_settings', 'date_format',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'DD.MM.YYYY'::character varying"),
               existing_nullable=False)
    op.alter_column('system_settings', 'default_currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'EUR'::character varying"),
               existing_nullable=False)
    op.alter_column('system_settings', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'de'::character varying"),
               existing_nullable=False)
    op.alter_column('system_settings', 'default_timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Europe/Berlin'::character varying"),
               existing_nullable=False)
    op.alter_column('system_settings', 'company_website',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'company_phone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'company_email',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'address_country',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Deutschland'::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'address_city',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'address_zip',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'address_street',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'tax_number',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'company_legal',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('system_settings', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'WorkmateOS'::character varying"),
               existing_nullable=False)
    op.create_index('ix_stripe_config_is_active', 'stripe_config', ['is_active'], unique=False)
    op.alter_column('stripe_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Config aktiv/inaktiv',
               existing_nullable=False)
    op.alter_column('stripe_config', 'test_mode',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Test Mode (true) or Live Mode (false)',
               existing_nullable=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Produktname/Dienstleistung'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Ausführliche Beschreibung'),
    sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Kurzbeschreibung für Rechnungen'),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='SKU / Artikelnummer'),
    sa.Column('category', postgresql.ENUM('private_customer', 'small_business', 'enterprise', 'hardware', 'software', 'consulting', 'support', 'development', 'other', name='productcategory'), autoincrement=False, nullable=False, comment='Produktkategorie'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Aktiv/Inaktiv'),
    sa.Column('is_service', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Ist eine Dienstleistung (vs. Produkt)'),
    sa.Column('price_type', postgresql.ENUM('hourly', 'fixed', 'monthly', 'project', 'per_unit', name='pricetype'), autoincrement=False, nullable=False, comment='Preistyp (Stundensatz, Pauschal, etc.)'),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False, comment='Preis pro Einheit (€)'),
    sa.Column('unit', sa.VARCHAR(length=50), server_default=sa.text("'Stück'::character varying"), autoincrement=False, nullable=False, comment='Einheit (Stunde, Stück, Projekt, Monat, etc.)'),
    sa.Column('default_tax_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('19.00'), autoincrement=False, nullable=False, comment='Standard-Steuersatz (%)'),
    sa.Column('min_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Mindestmenge'),
    sa.Column('max_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Maximalmenge'),
    sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Interne Notizen (nicht auf Rechnung)'),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('sku', name='products_sku_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    # ### end Alembic commands ###