"""Add HR leave management tables (complete)

Revision ID: 578d03552aae
Revises: a8904a298e14
Create Date: 2026-01-08 16:11:41.271843+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578d03552aae'
down_revision: Union[str, None] = 'a8904a298e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_leave_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vacation_days', sa.Integer(), nullable=False),
    sa.Column('sick_days', sa.Integer(), nullable=False),
    sa.Column('parental_days', sa.Integer(), nullable=False),
    sa.Column('carryover_allowed', sa.Boolean(), nullable=False),
    sa.Column('max_carryover_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_policy_name', 'hr_leave_policies', ['name'], unique=False)
    op.create_table('hr_leave_balances',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vacation_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacation_remaining', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sick_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sick_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('other_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('other_used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['hr_leave_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_balance_employee_id', 'hr_leave_balances', ['employee_id'], unique=False)
    op.create_index('ix_leave_balance_employee_year', 'hr_leave_balances', ['employee_id', 'year'], unique=False)
    op.create_table('hr_leave_requests',
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('half_day_start', sa.Boolean(), nullable=False),
    sa.Column('half_day_end', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("leave_type IN ('vacation', 'sick', 'unpaid', 'parental', 'bereavement', 'training', 'remote', 'other')", name='check_leave_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'cancelled')", name='check_leave_status'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_request_employee_id', 'hr_leave_requests', ['employee_id'], unique=False)
    op.create_index('ix_leave_request_start_date', 'hr_leave_requests', ['start_date'], unique=False)
    op.create_index('ix_leave_request_status', 'hr_leave_requests', ['status'], unique=False)
    op.create_index('ix_leave_request_type', 'hr_leave_requests', ['leave_type'], unique=False)
    op.create_table('hr_absence_calendar',
    sa.Column('absence_date', sa.Date(), nullable=False),
    sa.Column('is_full_day', sa.Boolean(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_request_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_request_id'], ['hr_leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_absence_calendar_date', 'hr_absence_calendar', ['absence_date'], unique=False)
    op.create_index('ix_absence_calendar_employee_id', 'hr_absence_calendar', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_absence_calendar_absence_date'), 'hr_absence_calendar', ['absence_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_absence_calendar_absence_date'), table_name='hr_absence_calendar')
    op.drop_index('ix_absence_calendar_employee_id', table_name='hr_absence_calendar')
    op.drop_index('ix_absence_calendar_date', table_name='hr_absence_calendar')
    op.drop_table('hr_absence_calendar')
    op.drop_index('ix_leave_request_type', table_name='hr_leave_requests')
    op.drop_index('ix_leave_request_status', table_name='hr_leave_requests')
    op.drop_index('ix_leave_request_start_date', table_name='hr_leave_requests')
    op.drop_index('ix_leave_request_employee_id', table_name='hr_leave_requests')
    op.drop_table('hr_leave_requests')
    op.drop_index('ix_leave_balance_employee_year', table_name='hr_leave_balances')
    op.drop_index('ix_leave_balance_employee_id', table_name='hr_leave_balances')
    op.drop_table('hr_leave_balances')
    op.drop_index('ix_leave_policy_name', table_name='hr_leave_policies')
    op.drop_table('hr_leave_policies')
    # ### end Alembic commands ###