"""Remove SevDesk and FinTS tables

Revision ID: e8aae60dde48
Revises: b2c3d4e5f6a7
Create Date: 2026-04-13 23:13:54.286585+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8aae60dde48'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sevdesk_bank_account_mappings_bank_account_id', table_name='sevdesk_bank_account_mappings')
    op.drop_index('ix_sevdesk_bank_account_mappings_sevdesk_id', table_name='sevdesk_bank_account_mappings')
    op.drop_table('sevdesk_bank_account_mappings')
    op.drop_index('ix_sevdesk_config_is_active', table_name='sevdesk_config')
    op.drop_table('sevdesk_config')
    op.drop_index('ix_sevdesk_invoice_mappings_invoice_id', table_name='sevdesk_invoice_mappings')
    op.drop_index('ix_sevdesk_invoice_mappings_sevdesk_id', table_name='sevdesk_invoice_mappings')
    op.drop_table('sevdesk_invoice_mappings')
    op.drop_index('ix_sevdesk_sync_history_started_at', table_name='sevdesk_sync_history')
    op.drop_index('ix_sevdesk_sync_history_status', table_name='sevdesk_sync_history')
    op.drop_index('ix_sevdesk_sync_history_sync_type', table_name='sevdesk_sync_history')
    op.drop_table('sevdesk_sync_history')
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Typ der Entität (Invoice, Payment, Expense, Customer, Contact, ...)',
               existing_comment='Typ der Entität (Invoice, Payment, Expense)',
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='Art der Aktion: create/update/delete/status_change/call/email/message/note/ticket_*/login/logout/upload',
               existing_comment='Art der Änderung (create, update, delete, status_change)',
               existing_nullable=False)
    op.alter_column('hr_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('hr_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_job_postings', 'remote',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hr_job_postings', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('hr_job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_job_postings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_reminders', 'invoice_id',
               existing_type=sa.UUID(),
               comment='Zugehörige Rechnung',
               existing_nullable=False)
    op.alter_column('invoice_reminders', 'level',
               existing_type=sa.INTEGER(),
               comment='Mahnstufe: 1=Erinnerung, 2=1. Mahnung, 3=2. Mahnung',
               existing_comment='1=Erinnerung, 2=1.Mahnung, 3=2.Mahnung',
               existing_nullable=False)
    op.alter_column('invoice_reminders', 'fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Mahngebühr in EUR',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoice_reminders', 'due_date',
               existing_type=sa.DATE(),
               comment='Neue Zahlungsfrist in der Mahnung',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Zeitpunkt des Versands (NULL = noch nicht gesendet)',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'pdf_path',
               existing_type=sa.TEXT(),
               comment='Pfad zur Mahnungs-PDF',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'notes',
               existing_type=sa.TEXT(),
               comment='Interne Notizen zur Mahnung',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_reminders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_articles', 'content',
               existing_type=sa.TEXT(),
               server_default=None,
               nullable=False)
    op.alter_column('kb_articles', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('kb_articles', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('kb_articles', 'helpful_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('kb_articles', 'not_helpful_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('kb_articles', 'pinned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('kb_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_categories', 'order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('kb_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_ticket_comments', 'is_internal',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('support_ticket_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('support_tickets', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('support_tickets', 'reporter_email',
               existing_type=sa.VARCHAR(length=255),
               comment='E-Mail des Erstellers für Antwort',
               existing_comment='E-Mail-Adresse des Erstellers (für Antwort per Mail)',
               existing_nullable=True)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_tickets_reporter_email', table_name='support_tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tickets_reporter_email', 'support_tickets', ['reporter_email'], unique=False)
    op.alter_column('support_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'reporter_email',
               existing_type=sa.VARCHAR(length=255),
               comment='E-Mail-Adresse des Erstellers (für Antwort per Mail)',
               existing_comment='E-Mail des Erstellers für Antwort',
               existing_nullable=True)
    op.alter_column('support_tickets', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'general'::character varying"),
               nullable=True)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'medium'::character varying"),
               nullable=True)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'open'::character varying"),
               nullable=True)
    op.alter_column('support_ticket_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_ticket_comments', 'is_internal',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('kb_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_categories', 'order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('kb_articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_articles', 'pinned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('kb_articles', 'not_helpful_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('kb_articles', 'helpful_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('kb_articles', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('kb_articles', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               nullable=True)
    op.alter_column('kb_articles', 'content',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               nullable=True)
    op.alter_column('invoice_reminders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_reminders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_reminders', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Interne Notizen zur Mahnung',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'pdf_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Pfad zur Mahnungs-PDF',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Zeitpunkt des Versands (NULL = noch nicht gesendet)',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Neue Zahlungsfrist in der Mahnung',
               existing_nullable=True)
    op.alter_column('invoice_reminders', 'fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Mahngebühr in EUR',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoice_reminders', 'level',
               existing_type=sa.INTEGER(),
               comment='1=Erinnerung, 2=1.Mahnung, 3=2.Mahnung',
               existing_comment='Mahnstufe: 1=Erinnerung, 2=1. Mahnung, 3=2. Mahnung',
               existing_nullable=False)
    op.alter_column('invoice_reminders', 'invoice_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Zugehörige Rechnung',
               existing_nullable=False)
    op.alter_column('hr_job_postings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_job_postings', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'draft'::character varying"),
               nullable=True)
    op.alter_column('hr_job_postings', 'remote',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hr_applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'received'::character varying"),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='Art der Änderung (create, update, delete, status_change)',
               existing_comment='Art der Aktion: create/update/delete/status_change/call/email/message/note/ticket_*/login/logout/upload',
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Typ der Entität (Invoice, Payment, Expense)',
               existing_comment='Typ der Entität (Invoice, Payment, Expense, Customer, Contact, ...)',
               existing_nullable=False)
    op.create_table('sevdesk_sync_history',
    sa.Column('sync_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Typ: invoice, bank_account, transaction, payment'),
    sa.Column('direction', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Richtung: push_to_sevdesk, pull_from_sevdesk'),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Status: success, failed, partial'),
    sa.Column('records_processed', sa.INTEGER(), autoincrement=False, nullable=False, comment='Anzahl verarbeiteter Datensätze'),
    sa.Column('records_success', sa.INTEGER(), autoincrement=False, nullable=False, comment='Anzahl erfolgreich synchronisierter Datensätze'),
    sa.Column('records_failed', sa.INTEGER(), autoincrement=False, nullable=False, comment='Anzahl fehlgeschlagener Datensätze'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Fehlermeldung'),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Startzeitpunkt'),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Endzeitpunkt'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sevdesk_sync_history_pkey')
    )
    op.create_index('ix_sevdesk_sync_history_sync_type', 'sevdesk_sync_history', ['sync_type'], unique=False)
    op.create_index('ix_sevdesk_sync_history_status', 'sevdesk_sync_history', ['status'], unique=False)
    op.create_index('ix_sevdesk_sync_history_started_at', 'sevdesk_sync_history', ['started_at'], unique=False)
    op.create_table('sevdesk_invoice_mappings',
    sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False, comment='WorkmateOS Invoice ID'),
    sa.Column('sevdesk_invoice_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='SevDesk Invoice ID'),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Zeitpunkt der letzten Synchronisation'),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Status der letzten Synchronisation'),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True, comment='Fehlermeldung bei fehlgeschlagener Synchronisation'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='sevdesk_invoice_mappings_invoice_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sevdesk_invoice_mappings_pkey'),
    sa.UniqueConstraint('invoice_id', name='sevdesk_invoice_mappings_invoice_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('sevdesk_invoice_id', name='sevdesk_invoice_mappings_sevdesk_invoice_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_sevdesk_invoice_mappings_sevdesk_id', 'sevdesk_invoice_mappings', ['sevdesk_invoice_id'], unique=False)
    op.create_index('ix_sevdesk_invoice_mappings_invoice_id', 'sevdesk_invoice_mappings', ['invoice_id'], unique=False)
    op.create_table('sevdesk_config',
    sa.Column('api_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='SevDesk API Token (verschlüsselt mit Fernet)'),
    sa.Column('auto_sync_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Automatische tägliche Synchronisation aktiviert?'),
    sa.Column('sync_invoices', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Rechnungen synchronisieren?'),
    sa.Column('sync_bank_accounts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Bankkonten synchronisieren?'),
    sa.Column('sync_transactions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Transaktionen synchronisieren?'),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Zeitpunkt der letzten erfolgreichen Synchronisation'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Konfiguration ist aktiv?'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sevdesk_config_pkey')
    )
    op.create_index('ix_sevdesk_config_is_active', 'sevdesk_config', ['is_active'], unique=False)
    op.create_table('sevdesk_bank_account_mappings',
    sa.Column('bank_account_id', sa.UUID(), autoincrement=False, nullable=False, comment='WorkmateOS BankAccount ID'),
    sa.Column('sevdesk_check_account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='SevDesk CheckAccount ID'),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Zeitpunkt der letzten Synchronisation'),
    sa.Column('sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Status der letzten Synchronisation'),
    sa.Column('sync_error', sa.TEXT(), autoincrement=False, nullable=True, comment='Fehlermeldung bei fehlgeschlagener Synchronisation'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name='sevdesk_bank_account_mappings_bank_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sevdesk_bank_account_mappings_pkey'),
    sa.UniqueConstraint('bank_account_id', name='sevdesk_bank_account_mappings_bank_account_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('sevdesk_check_account_id', name='sevdesk_bank_account_mappings_sevdesk_check_account_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_sevdesk_bank_account_mappings_sevdesk_id', 'sevdesk_bank_account_mappings', ['sevdesk_check_account_id'], unique=False)
    op.create_index('ix_sevdesk_bank_account_mappings_bank_account_id', 'sevdesk_bank_account_mappings', ['bank_account_id'], unique=False)
    # ### end Alembic commands ###