"""Add Stripe integration

Revision ID: a1b2c3d4e5f6
Revises: be8fda96d0d9
Create Date: 2026-01-03 01:22:00.000000+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'be8fda96d0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create stripe_config table
    op.create_table('stripe_config',
        sa.Column('publishable_key', sa.String(length=255), nullable=False, comment='Stripe Publishable Key (pk_test_... or pk_live_...)'),
        sa.Column('secret_key', sa.String(length=255), nullable=False, comment='Stripe Secret Key (ENCRYPTED: sk_test_... or sk_live_...)'),
        sa.Column('webhook_secret', sa.String(length=255), nullable=True, comment='Webhook Signing Secret (whsec_...)'),
        sa.Column('test_mode', sa.Boolean(), server_default='true', nullable=False, comment='Test Mode (true) or Live Mode (false)'),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Config aktiv/inaktiv'),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stripe_config_is_active', 'stripe_config', ['is_active'], unique=False)

    # Add stripe_payment_intent_id to payments table
    op.add_column('payments',
        sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True, comment='Stripe Payment Intent ID (pi_...)')
    )
    op.create_unique_constraint('uq_payments_stripe_payment_intent_id', 'payments', ['stripe_payment_intent_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove stripe_payment_intent_id from payments table
    op.drop_constraint('uq_payments_stripe_payment_intent_id', 'payments', type_='unique')
    op.drop_column('payments', 'stripe_payment_intent_id')

    # Drop stripe_config table
    op.drop_index('ix_stripe_config_is_active', table_name='stripe_config')
    op.drop_table('stripe_config')

    # ### end Alembic commands ###
