"""Add SevDesk integration models

Revision ID: be8fda96d0d9
Revises: c2b2fce85638
Create Date: 2026-01-02 22:31:08.737833+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be8fda96d0d9'
down_revision: Union[str, None] = 'c2b2fce85638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sevdesk_config',
    sa.Column('api_token', sa.String(length=500), nullable=False, comment='SevDesk API Token (verschlüsselt mit Fernet)'),
    sa.Column('auto_sync_enabled', sa.Boolean(), server_default='false', nullable=False, comment='Automatische tägliche Synchronisation aktiviert?'),
    sa.Column('sync_invoices', sa.Boolean(), server_default='true', nullable=False, comment='Rechnungen synchronisieren?'),
    sa.Column('sync_bank_accounts', sa.Boolean(), server_default='true', nullable=False, comment='Bankkonten synchronisieren?'),
    sa.Column('sync_transactions', sa.Boolean(), server_default='true', nullable=False, comment='Transaktionen synchronisieren?'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True, comment='Zeitpunkt der letzten erfolgreichen Synchronisation'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Konfiguration ist aktiv?'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sevdesk_config_is_active', 'sevdesk_config', ['is_active'], unique=False)
    op.create_table('sevdesk_sync_history',
    sa.Column('sync_type', sa.String(length=50), nullable=False, comment='Typ: invoice, bank_account, transaction, payment'),
    sa.Column('direction', sa.String(length=50), nullable=False, comment='Richtung: push_to_sevdesk, pull_from_sevdesk'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: success, failed, partial'),
    sa.Column('records_processed', sa.Integer(), nullable=False, comment='Anzahl verarbeiteter Datensätze'),
    sa.Column('records_success', sa.Integer(), nullable=False, comment='Anzahl erfolgreich synchronisierter Datensätze'),
    sa.Column('records_failed', sa.Integer(), nullable=False, comment='Anzahl fehlgeschlagener Datensätze'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Fehlermeldung'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='Startzeitpunkt'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Endzeitpunkt'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sevdesk_sync_history_started_at', 'sevdesk_sync_history', ['started_at'], unique=False)
    op.create_index('ix_sevdesk_sync_history_status', 'sevdesk_sync_history', ['status'], unique=False)
    op.create_index('ix_sevdesk_sync_history_sync_type', 'sevdesk_sync_history', ['sync_type'], unique=False)
    op.create_table('sevdesk_bank_account_mappings',
    sa.Column('bank_account_id', sa.Uuid(), nullable=False, comment='WorkmateOS BankAccount ID'),
    sa.Column('sevdesk_check_account_id', sa.String(length=50), nullable=False, comment='SevDesk CheckAccount ID'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Zeitpunkt der letzten Synchronisation'),
    sa.Column('sync_status', sa.String(length=50), nullable=False, comment='Status der letzten Synchronisation'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Fehlermeldung bei fehlgeschlagener Synchronisation'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id'),
    sa.UniqueConstraint('sevdesk_check_account_id')
    )
    op.create_index('ix_sevdesk_bank_account_mappings_bank_account_id', 'sevdesk_bank_account_mappings', ['bank_account_id'], unique=False)
    op.create_index('ix_sevdesk_bank_account_mappings_sevdesk_id', 'sevdesk_bank_account_mappings', ['sevdesk_check_account_id'], unique=False)
    op.create_table('sevdesk_invoice_mappings',
    sa.Column('invoice_id', sa.Uuid(), nullable=False, comment='WorkmateOS Invoice ID'),
    sa.Column('sevdesk_invoice_id', sa.String(length=50), nullable=False, comment='SevDesk Invoice ID'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Zeitpunkt der letzten Synchronisation'),
    sa.Column('sync_status', sa.String(length=50), nullable=False, comment='Status der letzten Synchronisation'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Fehlermeldung bei fehlgeschlagener Synchronisation'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('sevdesk_invoice_id')
    )
    op.create_index('ix_sevdesk_invoice_mappings_invoice_id', 'sevdesk_invoice_mappings', ['invoice_id'], unique=False)
    op.create_index('ix_sevdesk_invoice_mappings_sevdesk_id', 'sevdesk_invoice_mappings', ['sevdesk_invoice_id'], unique=False)
    op.drop_index('ix_time_entries_employee_id', table_name='time_entries')
    op.drop_index('ix_time_entries_project_id', table_name='time_entries')
    op.drop_index('ix_time_entries_start_time', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index('ix_working_hours_templates_employee_id', table_name='working_hours_templates')
    op.drop_table('working_hours_templates')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_table('products')
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_invoice_line_items_deleted_at', table_name='invoice_line_items')
    op.drop_index('ix_invoices_deleted_at', table_name='invoices')
    op.drop_index('ix_payments_deleted_at', table_name='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payments_deleted_at', 'payments', ['deleted_at'], unique=False)
    op.create_index('ix_invoices_deleted_at', 'invoices', ['deleted_at'], unique=False)
    op.create_index('ix_invoice_line_items_deleted_at', 'invoice_line_items', ['deleted_at'], unique=False)
    op.alter_column('bank_transactions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bank_accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Produktname/Dienstleistung'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Ausführliche Beschreibung'),
    sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Kurzbeschreibung für Rechnungen'),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='SKU / Artikelnummer'),
    sa.Column('category', postgresql.ENUM('private_customer', 'small_business', 'enterprise', 'hardware', 'software', 'consulting', 'support', 'development', 'other', name='productcategory'), autoincrement=False, nullable=False, comment='Produktkategorie'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Aktiv/Inaktiv'),
    sa.Column('is_service', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False, comment='Ist eine Dienstleistung (vs. Produkt)'),
    sa.Column('price_type', postgresql.ENUM('hourly', 'fixed', 'monthly', 'project', 'per_unit', name='pricetype'), autoincrement=False, nullable=False, comment='Preistyp (Stundensatz, Pauschal, etc.)'),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False, comment='Preis pro Einheit (€)'),
    sa.Column('unit', sa.VARCHAR(length=50), server_default=sa.text("'Stück'::character varying"), autoincrement=False, nullable=False, comment='Einheit (Stunde, Stück, Projekt, Monat, etc.)'),
    sa.Column('default_tax_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('19.00'), autoincrement=False, nullable=False, comment='Standard-Steuersatz (%)'),
    sa.Column('min_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Mindestmenge'),
    sa.Column('max_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Maximalmenge'),
    sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Interne Notizen (nicht auf Rechnung)'),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('sku', name='products_sku_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_table('working_hours_templates',
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('tuesday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('wednesday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('thursday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('friday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('saturday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('sunday_hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('weekly_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False, comment='Total hours per week'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='working_hours_templates_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='working_hours_templates_pkey')
    )
    op.create_index('ix_working_hours_templates_employee_id', 'working_hours_templates', ['employee_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True, comment='Optional - for internal time without project'),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True, comment='Duration in minutes'),
    sa.Column('billable', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Can this time be billed to customer?'),
    sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Rate for this entry'),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True, comment='What was worked on'),
    sa.Column('task_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='development, meeting, support, documentation, etc.'),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_invoiced', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='time_entries_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='time_entries_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='time_entries_pkey')
    )
    op.create_index('ix_time_entries_start_time', 'time_entries', ['start_time'], unique=False)
    op.create_index('ix_time_entries_project_id', 'time_entries', ['project_id'], unique=False)
    op.create_index('ix_time_entries_employee_id', 'time_entries', ['employee_id'], unique=False)
    op.drop_index('ix_sevdesk_invoice_mappings_sevdesk_id', table_name='sevdesk_invoice_mappings')
    op.drop_index('ix_sevdesk_invoice_mappings_invoice_id', table_name='sevdesk_invoice_mappings')
    op.drop_table('sevdesk_invoice_mappings')
    op.drop_index('ix_sevdesk_bank_account_mappings_sevdesk_id', table_name='sevdesk_bank_account_mappings')
    op.drop_index('ix_sevdesk_bank_account_mappings_bank_account_id', table_name='sevdesk_bank_account_mappings')
    op.drop_table('sevdesk_bank_account_mappings')
    op.drop_index('ix_sevdesk_sync_history_sync_type', table_name='sevdesk_sync_history')
    op.drop_index('ix_sevdesk_sync_history_status', table_name='sevdesk_sync_history')
    op.drop_index('ix_sevdesk_sync_history_started_at', table_name='sevdesk_sync_history')
    op.drop_table('sevdesk_sync_history')
    op.drop_index('ix_sevdesk_config_is_active', table_name='sevdesk_config')
    op.drop_table('sevdesk_config')
    # ### end Alembic commands ###