"""add products table

Revision ID: d13ce3a3941e
Revises: rzjbj0ur1dz2
Create Date: 2026-01-01 23:56:01.492578+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13ce3a3941e'
down_revision: Union[str, None] = 'rzjbj0ur1dz2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Kundentyp: creator, individual, business, government',
               existing_comment='Kundentyp: business, individual, government',
               existing_nullable=True)
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt hashed password for local auth',
               existing_nullable=True)
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt hashed password for local auth',
               existing_nullable=True)
    op.alter_column('customers', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='Kundentyp: business, individual, government',
               existing_comment='Kundentyp: creator, individual, business, government',
               existing_nullable=True)
    # ### end Alembic commands ###